workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get flutter packages
        script: |
          flutter pub get
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
